# Rebuild the QA sheet: the existing cases with their recorded results, plus the
# functionality added since it was written. Emitted through the csv module so
# commas inside a sentence stop being a quoting accident, and written as UTF-8
# with a BOM so Excel opens it without turning every arrow into "a-hat".
import csv, sys

H = ["ID","Plane","Area","Test Case","Steps","Expected","Priority","Result","Notes"]
R = []
def row(*a): R.append(list(a) + [""] * (9 - len(a)))

# ── Host ────────────────────────────────────────────────────────────────────
row("H-01","Host","Auth","Sign in as owner","Open host URL -> admin@techsme.com / password -> Sign in","Lands on Overview; sidebar + top bar render","P1")
row("H-02","Host","Auth","Reject wrong password","Admin email + wrong password -> Sign in","Clear error message; no session created","P1")
row("H-03","Host","Auth","Session expiry -> login","With an expired/cleared session, open /tenants","Auto-redirects to the login screen (no error panel)","P1")
row("H-04","Host","Auth","Sign out","Click sign out in the sidebar","Returns to login; protected pages inaccessible","P2")
row("H-05","Host","Overview","KPI tiles populate","Open Overview","Tenants, MRR, active/past-due show real numbers (not all 0 / dash)","P1")
row("H-06","Host","Overview","Recurring revenue + attention","Review Overview cards","MRR by currency listed; 'needs attention' shows the past-due tenant","P2")
row("H-07","Host","Overview","Recent activity + system status","Scroll Overview","Audit activity feed populated; system status reads Healthy","P2")
row("H-08","Host","Tenants","List all tenants","Open Tenants","All customer orgs listed with edition, status, region, seats","P1")
row("H-09","Host","Tenants","Filter by status","Click Active / Trial / Suspended tabs","List filters correctly to the chosen status","P2")
row("H-10","Host","Tenants","Search","Type a name in search","List narrows to matches","P3")
row("H-11","Host","Tenants","Open tenant drawer","Click a tenant row","Drawer shows detail + real usage/entitlement counts","P1")
row("H-12","Host","Tenants","Create tenant","New tenant -> name, subdomain, owner email, edition -> Create","Tenant created; owner credentials + Open-workspace link shown","P1")
row("H-13","Host","Tenants","Suspend / restore","Suspend a tenant, then restore","Status flips; audited; reversible","P2")
row("H-14","Host","Tenants","Impersonate","Click impersonate on a tenant","Opens that tenant workspace as its owner (audited)","P2")
row("H-15","Host","Subscriptions","Billing summary","Open Subscriptions","MRR, status counts, billing health all populated","P1")
row("H-16","Host","Subscriptions","Invoices list","Review invoices","Invoices with numbers + paid/open status (no raw UUIDs)","P2")
row("H-17","Host","Subscriptions","Invoice actions","On an open invoice -> Retry / Remind","Action succeeds with a confirmation toast","P3")
row("H-18","Host","Editions","Edition cards + counts","Open Editions","Each edition card shows module/feature/tenant counts","P1")
row("H-19","Host","Editions","Feature matrix","Open the matrix","Editions x features grid renders with cell states","P2")
row("H-20","Host","Editions","Edit edition features","Open an edition -> toggle a feature -> Save","Change persists; matrix reflects it","P2")
row("H-21","Host","Features","Feature catalog","Open Features","Features grouped by category; type/status shown","P2")
row("H-22","Host","Features","Create feature","Add feature -> key, name, type -> Save","Feature appears in the catalog","P3")
row("H-23","Host","Pricing","Edition prices","Open Pricing","Each edition shows real monthly/annual prices (not 'Custom')","P1")
row("H-24","Host","Pricing","Edit a price","Edit an edition price -> Save","New amount persists and displays formatted","P2")
row("H-25","Host","Pricing","Usage rates + coupons","Review usage rates / coupons","Metered rates listed; coupon create works","P3")
row("H-26","Host","Observability","Queues + workers","Open Observability","Queue depth, worker heartbeats, throughput chart render","P1")
row("H-27","Host","Observability","AI health","Review AI health panel","Providers/models with success rate + latency shown","P2")
row("H-28","Host","Observability","Failed jobs","Review failed jobs (if any) -> Retry/Resolve","Tenant shown by name (not UUID); actions work","P2")
row("H-29","Host","Audit","Audit log list + filter","Open Audit -> filter by action/date","Events listed; filter narrows results","P2")
row("H-30","Host","Audit","Verify chain","Click Verify audit chain","Reports chain integrity OK","P1")
row("H-31","Host","Audit","Export","Click export","Audit export produced/downloaded","P3")
row("H-32","Host","Notifications","Inbox + bell","Open Notifications / bell","Inbox populated; unread badge count correct","P2")
row("H-33","Host","Notifications","Mark read / read all","Mark one, then all read","Unread count decrements to 0","P3")
row("H-34","Host","Notifications","Compose broadcast","Compose -> audience -> Send","Broadcast recorded; audience preview correct","P3")
row("H-35","Host","Users & roles","Host users list","Open Host users & roles","Admin user + roles + permission matrix render","P2")
row("H-36","Host","Users & roles","Add host user","Add user -> email, role -> Save","User created; can sign in","P2")
row("H-37","Host","Users & roles","Create/edit role","New role -> pick permissions -> Save","Role created; permission counts correct; system roles read-only","P2")
row("H-38","Host","Settings","General / Security tabs","Open Settings tabs","Values render; no 'not wired' dev disclaimers","P2")
row("H-39","Host","Settings","AI providers / Email","Review AI + Email tabs","Providers/routing/domains manageable; no secrets leaked","P3")
row("H-40","Host","UX/Responsive","Sidebar collapse + mobile","Toggle collapse; shrink window < 860px","Collapses to rail; hamburger drawer on mobile; tables scroll","P2")
row("H-41","Host","UX/Copy","No placeholder/dev copy","Skim every page","No 'coming soon', 'localhost', TODO, spec-refs, raw UUIDs as labels","P1")

# ── Tenant: existing cases, results carried forward ─────────────────────────
row("T-01","Tenant","Auth","Sign in as owner","Open the tenant URL -> owner@cedarstone.build / password -> Sign in","Lands on Dashboard; workspace renders as 'Cedar & Stone Builders'","P1","PASS")
row("T-02","Tenant","Auth","Reject wrong password","Wrong password -> Sign in","Clear error; no session created","P1","PASS")
row("T-03","Tenant","Auth","Sign-in throttling","Fail sign-in four times inside a minute","Fourth attempt is rate-limited (429), not accepted","P2","PASS")
row("T-04","Tenant","Auth","Session expiry -> login","Expired session -> open any page","Auto-redirect to /login","P1","PASS")
row("T-05","Tenant","Auth","Host admin rejected","Try a Host staff email on the tenant","Rejected - separate identity pool","P2","PASS")
row("T-06","Tenant","Language","Switcher sits before Search","Look at the top bar","Language control is left of the Search field on every screen","P1","PASS")
row("T-07","Tenant","Language","Arabic switches to RTL","Top bar -> Arabic","UI translates; dir=rtl; layout mirrors; digits stay Western","P1","PASS")
row("T-08","Tenant","Language","French keeps LTR","Top bar -> Francais","UI translates; direction stays LTR; no clipped labels","P1","PASS")
row("T-09","Tenant","Language","No raw keys in any locale","Walk the chain and Admin in all three languages","No untranslated identifiers such as 'bundle.loading' on screen","P2","PASS")
row("T-10","Tenant","Language","Per-user override beats workspace default","Admin sets the workspace default; a user picks a different language","The user's choice wins and survives reload; others keep the default","P1","PASS")
row("T-11","Tenant","Dashboard","Greeting + review queue","Open Dashboard","Greets the signed-in person; 'Needs your review' lists real pending items","P1","PASS")
row("T-12","Tenant","Dashboard","Chain bundles hydrate progressively","Open Dashboard on a workspace with several projects","Cards fill in as each project resolves - no all-or-nothing skeleton","P2","PASS")
row("T-13","Tenant","Dashboard","Command palette","Cmd-K / Ctrl-K -> type a screen name","Palette opens and navigates there","P2","PASS")
row("T-14","Tenant","Projects","List projects","Open Projects","Portfolio listed with code, client, chain stage, status","P1","PASS")
row("T-15","Tenant","Projects","Create project","New project -> name, code, client -> Create","Created on the domain's lifecycle; opens the workspace","P1","PASS")
row("T-16","Tenant","Projects","Archive project","Trash icon on a row -> confirm","Removed from the list; history retained; audited","P2","PASS")
row("T-17","Tenant","Chain","Chain progress on the project","Open a project","'Chain progress' shows Documents / Tender / Drawings / Specs / BOQ / Estimate / Schedule / Procurement with per-stage status","P1","PASS")
row("T-18","Tenant","Chain","Stage tabs open their own surface","Click each stage tab in turn","Each renders its purpose-built surface, not a generic table; none errors","P1","PASS")
row("T-19","Tenant","Chain","Stage status is honest","Compare a stage chip against its artifacts","Complete / Needs review / Processing / Pending match the underlying records","P2","PASS")
row("T-20","Tenant","Documents","Upload + ingest","Documents -> upload a tender PDF","File ingested; friendly type and status; page text extracted","P1","PASS")
row("T-21","Tenant","Documents","Document text reaches the agents","Run a stage that reads documents after uploading","Output references the uploaded content - not generic filler","P1","PASS")
row("T-22","Tenant","BIM Studio","All disciplines present","Drawings -> BIM Studio","Ribbon shows Architecture, Structural, Civil, Electrical, Mechanical, Plumbing, Fire with their catalog items","P1","PASS")
row("T-23","Tenant","BIM Studio","Place an element","Pick a catalog item, e.g. Wall","Element is added, drawn on the plan, and counted in the legend","P1","PASS")
row("T-24","Tenant","BIM Studio","Walls are legible on the plan","Draw walls and partitions","They read as dark bands against the slab - not invisible on the sheet","P1","PASS")
row("T-25","Tenant","BIM Studio","Undo / redo","Ctrl-Z then Ctrl-Shift-Z","Last command reverses and reapplies","P2","PASS")
row("T-26","Tenant","BIM Studio","Save with concurrency check","Save; then save again from a stale second tab","First save succeeds; the stale one is refused, not silently overwritten","P1","PASS")
row("T-27","Tenant","BIM Studio","One canvas only","Scroll the Drawings stage","BIM Studio is the only authored canvas; the takeoff register is a table below it","P2","PASS",
    "Earlier note 'showing on the right not below' was the CAD facts panel beside the issued sheet, not the register - the register is below. Re-confirm.")
row("T-28","Tenant","BIM assistant","Draw from a prompt","Type 'Draw a 12 by 8 m clinic with a corridor, then doors and windows' -> Draw","Model appears: closed external walls, two corridor partitions, hosted doors and windows","P1","PASS")
row("T-29","Tenant","BIM assistant","Reports a missing API key plainly","Unset ANTHROPIC_API_KEY on the worker -> Draw","Clear message that the key is not set - no silent no-op, no stack trace","P1","","Previously 'Unable to find API Key'. Retest: the key lives ONLY on the worker (see T-88), so unset it in the worker service, not the app.")
row("T-30","Tenant","BIM assistant","Specialist scoping","Choose Electrical -> ask for lighting","Only electrical elements are added; it cannot clear the model or place another discipline","P2","PASS")
row("T-31","Tenant","BIM assistant","Nothing saved on a failed run","Interrupt a draw mid-way","The model is unchanged - commands persist once, at the end","P2","PASS")
row("T-32","Tenant","BIM assistant","Audited","Draw, then open Trace","A bim.agent entry records the specialist and instruction","P3","PASS")
row("T-33","Tenant","Takeoff","Measure into BOQ","BIM Studio -> Measure into BOQ","One drawing_measurement per measured item, as source 'human' (no review needed)","P1","PASS")
row("T-34","Tenant","Takeoff","Quantities net openings","Check a wall carrying windows","Elevational area = length x height less each opening; the working shows in Method","P1","","Open the measurement row -> the Method field. It is now editable too (see T-105).")
row("T-35","Tenant","Takeoff","Re-measuring supersedes","Edit the model -> Measure again","Previous BIM-derived measurements are superseded, not duplicated","P2","FAIL","Open defect.")
row("T-36","Tenant","Takeoff","Takeoff register","Scroll below the Studio","Measurements listed with quantity, confidence and status; any row can be opened","P1","PASS")
row("T-37","Tenant","CAD","DXF is parsed on upload","Documents -> upload a .dxf","Ingested as CAD, not as text; the row shows units, layer / block / sheet counts","P1","PASS")
row("T-38","Tenant","CAD","DWG is parsed with no extra setup","Upload a .dwg with no ODA File Converter configured","Parsed via the bundled LibreDWG; units, layers, blocks and footprint all read","P1","","Footprint appears in the Issued drawings panel beside the sheet, and only when a closed outline was found. Retest there.")
row("T-39","Tenant","CAD","An unreadable drawing fails loudly","Upload a corrupt or unsupported drawing","Marked failed with a message telling the estimator to re-save as DXF - never silently ingested as garbage","P2","PASS")
row("T-40","Tenant","CAD","Issued drawings panel","Drawings -> Issued drawings","The sheet renders, with units, footprint, block counts and per-layer metres beside it","P1","PASS")
row("T-41","Tenant","CAD","Footprint uses the largest outline, not the sum","Compare the stated footprint against the drawing's real overall dimensions","Matches L x W; it is not the inflated sum of every closed outline on the layer","P1","PASS")
row("T-42","Tenant","CAD","Unitless drawings are not converted","Upload a drawing with no $INSUNITS","Lengths and areas are NOT presented as m/m2 - the agent is told the units are unstated","P2")
row("T-43","Tenant","CAD","Takeoff cites the drawing","Run the Drawings workflow after uploading a .dxf","Each measurement's Method names the layer or block it came from, e.g. 'count of DOOR_SINGLE_900 = 5 (A-DOOR)'","P1","FAIL","Open defect.")
row("T-44","Tenant","CAD","Nothing is invented","Ask for a quantity the drawing cannot support, e.g. wall area with no height","Returns provisional with a stated reason rather than a fabricated number","P1","FAIL","Open defect.")
row("T-45","Tenant","CAD","Derivation from a drawing note","Include a thickness note such as 'SLAB 200mm THK'","Volume = area x thickness with the formula and both inputs written into Method","P1","FAIL","Open defect.")
row("T-46","Tenant","CAD","BOQ inherits the CAD quantities","Run the BOQ stage after confirming measurements","Counted, linear and area lines carry the drawing's numbers and cite their layer or block","P1","PASS")
row("T-47","Tenant","CAD","Programme is driven by those quantities","Run the Schedule stage","Activities name the driving quantity and durations follow from it, sequenced by construction logic","P1","BLOCKED","Blocked behind T-43/T-44/T-45.")
row("T-48","Tenant","CAD","Fanned-out stages get the same evidence","Inspect a per-sheet takeoff job's envelope","Documents and CAD facts are present on child jobs, not only on single-dispatch ones","P2")
row("T-49","Tenant","CAD","The parser holds no credentials","Inspect the cad container","No database env, uploads mounted read-only, runs as a non-root user","P2")
row("T-50","Tenant","Stages","Tender surface","Open Tender","Scope, dates and conditions readable; proposals reviewable in place","P1","PASS")
row("T-51","Tenant","Stages","Specs surface","Open Specs","Specification clauses grouped and traceable to their document page","P1","PASS")
row("T-52","Tenant","Stages","BOQ surface","Open BOQ","Items grouped by division with normalised units; quantities trace to measurements","P1","PASS")
row("T-53","Tenant","Stages","Estimate surface","Open Estimate","Rate x quantity = amount on every line; totals foot correctly","P1","PASS")
row("T-54","Tenant","Stages","Schedule surface","Open Schedule","Activities sequenced with durations derived from quantities and output rates","P1","PASS")
row("T-55","Tenant","Stages","Procurement surface","Open Procurement","Packages listed against their BOQ items","P2")
row("T-56","Tenant","Review","Confirm on the producing stage","Accept a pending proposal from its own stage tab","Confirmed there - no separate Review screen; gate resumes","P1")
row("T-57","Tenant","Review","Edit marks downstream stale","Correct a CONFIRMED quantity: open the row -> Correct this -> change the number -> Save correction","New version created; the old one is superseded; dependent artifacts flagged stale and the toast says how many","P2","","Was not reachable before - a confirmed record was read-only in the drawer. See T-104.")
row("T-58","Tenant","Review","Accept all high-confidence","Use Accept all where offered","Only high-confidence proposals are confirmed; flagged ones remain","P2")
row("T-59","Tenant","Runs","Runs list","Project -> Runs","Runs listed by friendly workflow name and status","P2")
row("T-60","Tenant","Runs","Run detail timeline","Open a run","Step timeline with gates; statuses correct; pauses at the scope gate","P1")
row("T-61","Tenant","Runs","Real agents produce real output","With a key set, run the chain on an uploaded tender","Each step takes real model time and its output differs per project - not identical stub text","P2")
row("T-62","Tenant","Runs","Re-run stale","Edit a confirmed artifact -> Re-run stale","Only stale-producing steps re-run; outputs superseded","P2")
row("T-63","Tenant","Copilot","Workspace Copilot","Sidebar -> Copilot","Answers with workspace context","P2","PASS")
row("T-64","Tenant","Copilot","Per-project Copilot","Open a project -> Ask Copilot","Answers from that project's own records; does not leak another project's data","P1","PASS")
row("T-65","Tenant","Trace","Artifact graph","Project -> Trace","Artifacts grouped by type with human labels, not bare UUIDs","P1","PASS")
row("T-66","Tenant","Trace","Lineage detail","Select an artifact","Provenance, producing job and model, and audit trail shown","P2","PASS")
row("T-67","Tenant","Trace","Verify audit chain","Click Verify audit chain","Reports the hash chain intact","P1","PASS")
row("T-68","Tenant","Colleagues","Personas roster","Project -> Colleagues","Personas listed with names; default marked","P2","PASS")
row("T-69","Tenant","Colleagues","Chat with a colleague","Send a message","Replies in scope; the review lens shows only in-scope items","P2","PASS")
row("T-70","Tenant","Standards","Rules + validate","Project -> Standards -> Validate","Rules listed; violations shown as readable fields","P2","PASS")
row("T-71","Tenant","Library","Add entry","Library -> Add entry -> collection + fields","Entry appears grouped by collection","P2","PASS")
row("T-72","Tenant","Library","Edit creates a version","Edit an entry -> Save","Version increments; history kept","P2","PASS")
row("T-73","Tenant","Library","Rate book reaches the estimator","Add a rate to a rate_book collection, then open a project -> Estimate -> run CostLogix","The estimate uses library rates rather than inventing them; the line's Rate source names the library entry","P2","",
    "Earlier note 'no estimate option': Estimate is a stage tab inside a project, not a Library action. Run it from the project.")
row("T-74","Tenant","Admin","Team + roles","Admin -> Team","People and roles listed; tiers shown as labels","P1","PASS")
row("T-75","Tenant","Admin","Add user","Add user -> email, role -> Add","User added; temporary password shown in a copyable panel","P1","PASS")
row("T-76","Tenant","Admin","Custom role CRUD","Create a role -> permissions -> Save; edit; delete","Custom role works; system roles stay read-only","P2","PASS")
row("T-77","Tenant","Admin","Branding","Admin -> Branding -> workspace name + brand colour -> Save","Name and colour apply across the app for everyone","P2","PASS")
row("T-78","Tenant","Admin","Workspace default language","Admin -> Branding -> language -> Save for everyone","New sessions without a personal choice open in that language","P2","PASS")
row("T-79","Tenant","Admin","Plan + usage","Admin -> Plan","Edition, seats, licensed products and usage shown; no dev URLs","P2","PASS")
row("T-80","Tenant","Settings","Profile + preferences","Settings -> Profile / Preferences","Name, currency, date format and theme persist","P2","PASS")
row("T-81","Tenant","Settings","Notifications","Settings -> Notifications -> toggle","Choices persist","P2","PASS")
row("T-82","Tenant","UX","Collapse + mobile","Toggle the sidebar; shrink below 860px","Rail collapse; off-canvas drawer; tables scroll; drawers go full-width","P2")
row("T-83","Tenant","UX","No placeholder or dev copy","Skim every page in all three languages","No 'Riverside' leftovers, section refs, 'walking-skeleton', or raw keys as titles","P1")
row("T-84","Tenant","UX","Errors read as errors","Trigger a failure, e.g. draw with no key","Message is styled as a failure, not a green success tick","P2")
row("T-85","Tenant","Data","Tenant isolation","Confirm only this tenant's data is visible","No cross-tenant projects, artifacts or users","P1","PASS")
row("T-86","Tenant","Data","Audit chain integrity","Work a project through the whole chain -> Verify","Chain verifies after many operations","P1","PASS")
row("T-87","Tenant","Data","End-to-end chain completeness","Upload a real tender and run every stage","Reaches Procurement with artifacts at each stage and nothing left pending","P1","PASS")
row("T-88","Tenant","Data","The API key never leaves the worker","Inspect the app container's environment","ANTHROPIC_API_KEY is absent there; only the worker holds it","P2")

# ── New: drawing editor ─────────────────────────────────────────────────────
row("T-89","Tenant","Drawing editor","Reachable as a workspace tool","Sidebar -> TOOLS -> Drawing editor","Opens /drawings with a project picker, a sheet picker and an Open-a-.dxf button","P1")
row("T-90","Tenant","Drawing editor","Deep link from DrawLogix","Drawings -> Issued drawings -> Edit & mark up","Opens the editor with that project and that sheet already selected","P1")
row("T-91","Tenant","Drawing editor","Issued drawing loads as real geometry","Pick a sheet","Linework and text draw on a dark canvas; the layer list is populated with per-layer object counts","P1")
row("T-92","Tenant","Drawing editor","Navigation","Wheel over the canvas; drag with the middle or right button; press Fit","Wheel zooms about the cursor; middle/right drag pans in any tool; Fit frames the drawing, ignoring stray far-off entities","P1")
row("T-93","Tenant","Drawing editor","Draw tools","Draw a line, polyline (Enter to finish), rectangle, circle and a text label","Each is added on the active layer and appears in the object count","P1")
row("T-94","Tenant","Drawing editor","Dimension","Dimension -> click two points -> click to place the dimension line","An aligned dimension is drawn on a DIMENSIONS layer, its value in the chosen unit","P1")
row("T-95","Tenant","Drawing editor","Object snap","Turn Object snap on; hover a line end, a midpoint and a crossing","A distinct green marker appears per snap type with a label; F3 toggles snapping off","P1")
row("T-96","Tenant","Drawing editor","Ortho and polar","Press F8, draw a line; press F10, draw another","F8 constrains to horizontal/vertical; F10 snaps to the polar increment; a tracking line is shown","P2")
row("T-97","Tenant","Drawing editor","Select and modify","Window-select, then Move, Copy, Rotate, Mirror, Scale and Erase","A ghost preview follows the cursor; the operation applies to the selection and the tool returns to Select","P1")
row("T-98","Tenant","Drawing editor","Hatch","Select a closed shape -> Hatch; or trace a boundary and press Enter","The area fills with 45-degree hatch lines on a HATCH layer","P2")
row("T-99","Tenant","Drawing editor","Layers","Toggle a layer off; click a layer name; filter the list","Hiding removes it from the canvas AND from snapping; clicking the name selects everything on it","P2")
row("T-100","Tenant","Drawing editor","Measure","Measure -> click a chain of points","Running total per segment and, from three points, an enclosed area, in the selected unit","P1")
row("T-101","Tenant","Drawing editor","Undo / redo","Ctrl-Z, Ctrl-Y after several edits","Every edit reverses and reapplies in order","P2")
row("T-102","Tenant","Drawing editor","Download DXF","Mark up a sheet -> Download DXF","A valid DXF downloads and reopens in AutoCAD / LibreCAD with the markup on its own layers","P1")
row("T-103","Tenant","Drawing editor","Save to project keeps the original","Mark up an issued sheet -> Save to project","A NEW file appears in Documents named '<sheet>-markup.dxf'; the original sheet is unchanged; the sidecar re-reads the new one","P1")
row("T-104","Tenant","Drawing editor","Open a .dxf from disk","Open a .dxf -> pick a local file","Loads without uploading anything; Save to project is not offered; Download DXF is","P2")
row("T-105","Tenant","Drawing editor","A .dwg from disk is refused clearly","Open a .dxf -> pick a local .dwg","Explains that a .dwg must be uploaded to a project first because the converter runs on the server","P2")
row("T-106","Tenant","Drawing editor","Unsaved markup is protected","Mark up, then try to close the tab","The browser warns before losing the markup","P3")
row("T-107","Tenant","Drawing editor","Canvas is never mirrored in Arabic","Switch to Arabic and open the editor","Page furniture flips to RTL; the drawing itself stays as drawn","P2")

# ── New: issued drawings presentation ───────────────────────────────────────
row("T-108","Tenant","Issued drawings","Schedules are folded, not stacked","Open a sheet carrying several extracted tables","Each table is one collapsed row showing its size; opening one scrolls inside its own box rather than stretching the page","P1")
row("T-109","Tenant","Issued drawings","A table is named after itself","Open a sheet whose schedule is titled, e.g. FINISH SCHEDULE","The heading reads the schedule's own title, with the CAD layer beside it as a chip - not the bare layer name","P2")
row("T-110","Tenant","Issued drawings","Room tags are counted, not tabulated","Open a floor plan whose room labels were read as a table","Shown as counted chips (e.g. BED ROOM x54), not hundreds of repeated cells","P2")
row("T-111","Tenant","Issued drawings","Notes list only notes","Open a sheet with keynote numbers on it","No bullets reading '1', '2', '3'; only text with words in it, capped with a show-all control","P2")

# ── New: correcting confirmed records ───────────────────────────────────────
row("T-112","Tenant","Review","A confirmed record can be corrected","Open any confirmed artifact from its stage -> Correct this","The fields become editable behind a warning that a new version supersedes this one and marks downstream stale","P1")
row("T-113","Tenant","Review","Corrections are audited as human","Save a correction -> open Trace","The new version's source is 'human', the old one reads superseded, and the edit is on the audit chain","P2")
row("T-114","Tenant","Review","Long text has room","Correct a spec clause, a narrative section, a tender scope or a BOQ note","The field is a multi-line box, not a single-line input","P2")
row("T-115","Tenant","Review","A rejected record stays closed","Open a rejected artifact","Read-only, with an explanation that nothing downstream depends on it","P3")
row("T-116","Tenant","Review","Correct an accepted measurement from the register","Drawings -> takeoff register -> an Accepted row -> Correct this","Opens the same drawer in correction mode; quantity, unit, location and method are all editable","P1")

# ── New: archived projects ──────────────────────────────────────────────────
row("T-117","Tenant","Projects","Archived projects are reachable","Archive a project, then scroll to the bottom of Projects","An 'Archived projects' section appears with a count; opening it lists them with the date archived","P2")
row("T-118","Tenant","Projects","Restore an archived project","Archived projects -> Restore","Returns to the main list with its chain and audit history intact; the section disappears when empty","P2")
row("T-119","Tenant","Projects","Restore is permissioned","Sign in as a role without project.archive","No Restore button; the API refuses the change","P3")

# ── New: submission cover ───────────────────────────────────────────────────
row("T-120","Tenant","Exports","Submission cover form","Project -> Overview -> Submission cover","Ref No., project number, name, location, client and 'Submitted to' are editable and persist","P1")
row("T-121","Tenant","Exports","Blank cover fields are counted, not hidden","Leave two fields empty","A chip states how many are blank, so they are filled before submission","P3")

# ── New: Excel exports ──────────────────────────────────────────────────────
row("T-122","Tenant","Exports","Priced BOQ workbook","BOQ -> Export Excel","Downloads a workbook with a Cover sheet, one sheet per division, and a Summary sheet","P1")
row("T-123","Tenant","Exports","The bill scrolls","Open a division sheet and scroll","Only the heading row is frozen; the whole bill scrolls - no block of branding pinned at the top","P1")
row("T-124","Tenant","Exports","Wrapped rows are fully visible","Find a long item description","The row is tall enough to show all of it; nothing is clipped to one line","P1")
row("T-125","Tenant","Exports","Cover carries the submission details","Open the Cover sheet","TechSME logo centred in the letterhead box; Ref No., project number, name, location, client, date and 'Submitted to' filled from the form","P1")
row("T-126","Tenant","Exports","Summary foots","Open the Summary sheet","Per-division totals, a grand total, unpriced counts, and a disclaimer when anything is unpriced","P1")
row("T-127","Tenant","Exports","Unpriced lines are marked, not zeroed","Export a bill with rates missing","Those cells read 'To be priced' on a tinted fill and are excluded from the total, which is declared provisional","P1")
row("T-128","Tenant","Exports","Work programme workbook","Schedule -> Export Excel","Downloads a Gantt: month and week header rows, coloured phase bars, milestone diamonds, critical path marked","P1")
row("T-129","Tenant","Exports","Programme header block","Open the programme sheet","Letterhead with the logo centred by column width, then the project details; panes frozen at the week row so bars scroll under fixed headings","P1")
row("T-130","Tenant","Exports","Exports open clean in Excel","Open both workbooks in desktop Excel","No repair prompt, no broken formulas, colours and borders as designed","P1")

# ── New: technical narrative ────────────────────────────────────────────────
row("T-131","Tenant","Narrative","Stage exists before Procurement","Open a project's tabs","A Technical Narrative stage sits between Schedule and Procurement","P2")
row("T-132","Tenant","Narrative","Seven sections, generated one at a time","Narrative -> Generate on a section","Only that section is written; the others are untouched","P1")
row("T-133","Tenant","Narrative","Sections are editable","Open a section -> Correct","The body is a multi-line editor and the correction supersedes the generated version","P2")
row("T-134","Tenant","Narrative","Download all","Narrative -> Download all","A single Markdown document with all seven sections in order","P2")

# ── Deployment ──────────────────────────────────────────────────────────────
row("D-01","Deployment","Infra","Both planes up","docker compose up on host + tenant","All containers healthy; apps serve 200","P1")
row("D-02","Deployment","Infra","Seed reproducible","Run seed scripts on a fresh volume","Catalog + demo tenant(s) created without error","P1")
row("D-03","Deployment","Infra","HTTPS (host)","Open the host over its domain","Valid TLS; login works; cookies stick","P1")
row("D-04","Deployment","Infra","HTTPS (tenant)","Open the tenant over its domain","Valid TLS; login works","P2")
row("D-05","Deployment","Infra","Reverse proxy","Both apps reachable behind nginx","Correct app served per hostname; no port clash","P2")
row("D-06","Deployment","Security","Secrets rotated","Inspect env/override","BETTER_AUTH_SECRET 32+, DB pw + service token not defaults","P1")
row("D-07","Deployment","Security","DB not exposed","Port scan the public IP","MySQL (3306/3307) not publicly reachable","P1")
row("D-08","Deployment","Security","Admin password changed","Change seeded admin password","Default demo password no longer valid","P1")
row("D-09","Deployment","Provisioning","Host -> tenant bootstrap","Create a tenant in the host","Tenant provisioned live in the tenant plane (not mirror)","P2")
row("D-10","Deployment","Ops","Logs + restart","Tail logs; restart a service","Logs clean; service recovers; data persists","P2")
row("D-11","Deployment","Ops","Update flow","Sync source -> docker compose up --build","New build deploys without data loss","P2")
row("D-12","Deployment","Ops","The build picks up new dependencies","Add a dependency, sync package.json + package-lock.json, rebuild","The npm install layer re-runs instead of reporting CACHED; the new module resolves","P1","",
    "Added after a deploy failed on 'Cannot resolve dxf-parser': package.json had not been copied, so Docker reused the cached deps layer.")
row("D-13","Deployment","Ops","The running container has the code you shipped","After a rebuild, list the built routes inside the container","The new route is present; a stale build is caught here rather than in the browser","P1")
row("D-14","Deployment","Perf","Basic load","Click through main pages","Pages respond < ~1s; no console errors","P2")
row("D-15","Deployment","Perf","A large drawing stays usable","Open a 13-sheet set's biggest drawing in the editor","Pan and zoom stay responsive; labels drop out when too small rather than stalling the frame","P2")
row("D-16","Deployment","Backup","DB volume backup","Dump the MySQL volume","Backup produced; restorable","P3")
row("D-17","Deployment","Compat","Cross-browser","Open in Chrome + one other","Renders + works in both","P3")

out = sys.argv[1]
# utf-8-sig: Excel on Windows reads a BOM-less UTF-8 CSV as the ANSI codepage,
# which is how the previous sheet ended up full of "a-hat" characters.
with open(out, "w", newline="", encoding="utf-8-sig") as fh:
    w = csv.writer(fh)
    w.writerow(H)
    w.writerows(R)

ids = [r[0] for r in R]
assert len(ids) == len(set(ids)), "duplicate ID"
print(f"{len(R)} cases -> {out}")
for plane in ("Host", "Tenant", "Deployment"):
    n = sum(1 for r in R if r[1] == plane)
    print(f"  {plane}: {n}")
print("  new since last sheet:", sum(1 for r in R if r[0] >= "T-089" and r[1] == "Tenant" and r[0].startswith("T-1")))
